### PR TITLE
Update Ledger Nano Device IDs

### PR DESCRIPTION
**Pull request by Redstoneguy129**
See
https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/

### CODE REVIEW

**Comment by wakiyamap** [comment]
First. Thanks pull request.
Hmmm......do you need WebUSB?

**Comment by Redstoneguy129** [comment]
No, you shouldn't. At least I don't think so.

**Comment by wakiyamap** [comment]
Oh, I understand.
It certainly seems to be required in newer versions of the library.
Thanks !!

**Comment by wakiyamap** [comment]
It seems to have been resolved in this commit(https://github.com/spesmilo/electrum/commit/b78cbcffd11364ed4651af1886d507b36bc1b013), so I'll revert once.

I don't have a ledger so I can't verify.

**Pull request merged**
